### ISSUE TITLE
Can't get the plugin to work

### ISSUE THREAD

**Issue by alexeyr** [erlware/rebar_vsn_plugin#23]
Could you add an example of a project using this plugin to the README? 

I've tried to activate it in https://github.com/alexeyr/erlang-sqlite3/tree/rebar_vsn but this doesn't seem to have any effect (from `Explanation` it isn't clear where the version string will be placed; I assumed `ebin/<app-name>.app`).

**Comment by ericbmerritt** [comment]
You have to replace the `vsn` tuple in your app.src with `{vsn, "semver"}`

**Comment by alexeyr** [comment]
I was going by

> The key change is having the version you wish to use `{vsn, "0.0.5"}` in the version field.

Is this only talking about stable versions or some other specific situations?

**Comment by ericbmerritt** [comment]
Yea. I noticed that that was misleading. I am going to update the readme. I was trying to say that when you hardcode a version its not usually truly representative of the version unless you  are very careful. Thats what this plugin is designed to fix.

**Comment by alexeyr** [comment]
Thanks! The behavior I expected would be that I'd get `1.1.0+build...` as the version, i.e. the same as `semver` but with the first part determined by `.app.src` instead of the Git tag.

**Comment by ericbmerritt** [comment]
Historically the plugin got called for all the apps in the system, but the target app and any/all dependencies. So we needed a way to distinguish those apps that where designed to be updated by the plugin and those that where not. This is the way we came up with.
