### ISSUE TITLE
Сompilation of a plugin

### ISSUE THREAD

**Issue by define-null** [erlware/rebar_vsn_plugin#9]
It should be mentioned that in order to use this plugin as a dep this section should be added to rebar.config:

``` erlang
{plugin_dir, "deps/rebar_vsn_plugin/src"}.
```

Without this section if we run 

```
rebar get-deps
rebar compile
```

All the code will be compiled but the plugin would not work, because at the compile of the application it wasnot already compiled. Plugin_dir will force compiling of a plugin and will load it at run-time.

**Comment by ericbmerritt** [comment]
ah, yes. My solution to that has been just to run compile twice the first time. This is a nicer solution though. I will add it to the readme.
